 setup :
5 weights connected to a single node , one bias and sigmoid as A.F. so it is a binary classification problem  

In [1]:
# model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out =self.linear(features)
    out=self.sigmoid(out)

    return out


In [2]:
#  creating dataset
features=torch.rand(10,5)
# model
model=Model(features.shape[1])
# call for forward pass
# model.forward(features)  OR
model(features)



tensor([[0.5567],
        [0.5779],
        [0.5964],
        [0.5337],
        [0.5176],
        [0.4971],
        [0.5648],
        [0.5428],
        [0.5374],
        [0.5962]], grad_fn=<SigmoidBackward0>)

In PyTorch, calling model(x) works because nn.Module defines __call__(), which internally calls model.forward(x) plus handles important things like autograd, hooks, and train/eval behavior.

Calling model.forward(x) directly skips this extra logic, so it’s not recommended.

In [4]:
model.linear.weight

Parameter containing:
tensor([[ 0.2018, -0.4113,  0.1441, -0.0320, -0.3995]], requires_grad=True)

In [3]:
model.linear.bias

Parameter containing:
tensor([0.4362], requires_grad=True)

In [6]:
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Another Example with hiden layer
5 in input layer , three in hidden layer and output with one node. So total 5*3+3*1=18 weights. And 3+1 = 4 bias.  
Activations: ReLu in Hidden Layer
Sigmoid in Output Layer

In [11]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out =self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmoid(out)
    return out


In [12]:
features=torch.rand(10,5)
# model
model=Model(features.shape[1])
# call for forward pass
# model.forward(features)  OR
model(features)

tensor([[0.6587],
        [0.6574],
        [0.6848],
        [0.6573],
        [0.6614],
        [0.6828],
        [0.6628],
        [0.6763],
        [0.6949],
        [0.6834]], grad_fn=<SigmoidBackward0>)

In [13]:
model.linear1.weight

Parameter containing:
tensor([[-0.4187, -0.1497, -0.3860, -0.3318,  0.4004],
        [-0.3996,  0.3986, -0.3147,  0.2956,  0.2414],
        [ 0.3001,  0.3130, -0.3038, -0.0097, -0.3945]], requires_grad=True)

In [14]:
model.linear2.weight

Parameter containing:
tensor([[-0.3259,  0.3928,  0.1111]], requires_grad=True)

In [15]:
model.linear1.bias

Parameter containing:
tensor([-0.3286,  0.2806,  0.2681], requires_grad=True)

In [16]:
model.linear2.bias

Parameter containing:
tensor([0.5176], requires_grad=True)

In [17]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Sequential Container

In [20]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )


  def forward(self,features):
    out =self.network(features)

    return out


In [21]:
features=torch.rand(10,5)
# model
model=Model(features.shape[1])
# call for forward pass
# model.forward(features)  OR
model(features)

tensor([[0.4886],
        [0.4886],
        [0.4886],
        [0.4886],
        [0.4886],
        [0.5007],
        [0.4886],
        [0.4886],
        [0.4886],
        [0.4886]], grad_fn=<SigmoidBackward0>)

# ***Training Pipeline Using NN Module***

In [22]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [25]:
df=pd.read_csv("breast-cancer.csv")
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [26]:
df.drop(columns=['id'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [27]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)


In [28]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [29]:
x_train

array([[ 0.30507926,  1.60728815,  0.28235686, ...,  0.62851628,
        -0.39707277,  0.59534494],
       [ 0.26820036, -0.08183151,  0.27578524, ..., -0.41767034,
        -0.07995382,  0.47393978],
       [-0.99135609,  0.9650834 , -0.99705616, ..., -1.22348585,
        -1.0809606 , -0.87310563],
       ...,
       [ 1.64123036,  1.45703647,  1.61311069, ...,  0.94290642,
         0.64557589,  0.05840304],
       [ 3.8057384 ,  1.7357291 ,  3.93371536, ...,  2.30577243,
        -0.41789371, -0.51440857],
       [-1.20922531, -0.83308989, -1.21679483, ..., -0.91306374,
        -0.09757154, -0.10163103]])

In [30]:
y_train

353    M
147    B
299    B
400    M
122    M
      ..
288    B
329    M
129    M
461    M
273    B
Name: diagnosis, Length: 455, dtype: object

In [33]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [34]:
y_test

array([0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0])

In [35]:
y_train

array([1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,

In [37]:
X_train_tensor = torch.from_numpy(x_train)
X_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [38]:
y_train_tensor.shape

torch.Size([455])

In [40]:
X_train_tensor.shape

torch.Size([455, 30])

In [39]:
X_test_tensor.shape

torch.Size([114, 30])

In [41]:
y_test_tensor.shape

torch.Size([114])

Defining the model

In [42]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out =self.linear(features)
    out=self.sigmoid(out)
    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [48]:
learning_rate=0.1
epoches=15

In [45]:
X_train_tensor = X_train_tensor.float()
X_test_tensor  = X_test_tensor.float()


In [49]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epoches):

  # forward pass
  y_pred = model(X_train_tensor)

  # # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # # backward pass
  loss.backward()

  # # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # # print loss in  each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6967173218727112
Epoch: 2, Loss: 0.69358891248703
Epoch: 3, Loss: 0.6907339096069336
Epoch: 4, Loss: 0.6881108283996582
Epoch: 5, Loss: 0.6856911778450012
Epoch: 6, Loss: 0.6834536194801331
Epoch: 7, Loss: 0.6813808083534241
Epoch: 8, Loss: 0.6794583201408386
Epoch: 9, Loss: 0.6776732206344604
Epoch: 10, Loss: 0.6760143041610718
Epoch: 11, Loss: 0.6744710206985474
Epoch: 12, Loss: 0.6730341911315918
Epoch: 13, Loss: 0.6716952919960022
Epoch: 14, Loss: 0.670446515083313
Epoch: 15, Loss: 0.6692806482315063


In [50]:
model.linear.weight

Parameter containing:
tensor([[ 0.1778,  0.0254,  0.1118, -0.0801, -0.0928,  0.0375, -0.1273,  0.0542,
          0.0787,  0.0464, -0.0998, -0.1121,  0.0146, -0.1221,  0.0493,  0.1782,
         -0.0026, -0.0866,  0.0260, -0.0605, -0.0134,  0.0500,  0.0638, -0.0876,
         -0.0516, -0.1255, -0.0086,  0.0460,  0.1135,  0.0163]],
       requires_grad=True)

In [51]:
model.linear.bias

Parameter containing:
tensor([-0.2972], requires_grad=True)

In [53]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item():.4f}")

# print(y_pred)

Accuracy: 0.5385


Using Built In Loss And Optimizer

In [68]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out =self.linear(features)
    out=self.sigmoid(out)
    return out




In [55]:
learning_rate=0.1
epoches=15

In [69]:
loss_function=nn.BCELoss()

In [70]:
X_train_tensor = X_train_tensor.float()
X_test_tensor  = X_test_tensor.float()
y_train_tensor = y_train_tensor.float()
y_test_tensor  = y_test_tensor.float()

In [71]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])
# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
# define loop
for epoch in range(epoches):

  # forward pass
  y_pred = model(X_train_tensor)

  # # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # # backward pass
  optimizer.zero_grad()
  loss.backward()

  # # parameters update
  # with torch.no_grad():
  #   model.linear.weight -= learning_rate * model.linear.weight.grad
  #   model.linear.bias -= learning_rate * model.linear.bias.grad

  # # # zero gradients
  # model.linear.weight.grad.zero_()
  # model.linear.bias.grad.zero_()

  optimizer.step()




  # # print loss in  each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7073627710342407
Epoch: 2, Loss: 0.5432119965553284
Epoch: 3, Loss: 0.45565131306648254
Epoch: 4, Loss: 0.40068814158439636
Epoch: 5, Loss: 0.3622491955757141
Epoch: 6, Loss: 0.3334767520427704
Epoch: 7, Loss: 0.3109198808670044
Epoch: 8, Loss: 0.2926320731639862
Epoch: 9, Loss: 0.27742278575897217
Epoch: 10, Loss: 0.26451849937438965
Epoch: 11, Loss: 0.25339260697364807
Epoch: 12, Loss: 0.24367286264896393
Epoch: 13, Loss: 0.23508766293525696
Epoch: 14, Loss: 0.22743390500545502
Epoch: 15, Loss: 0.22055597603321075


In [75]:
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {accuracy.item():.4f}")

# print(y_pred)

Accuracy: 0.5054
