Import


In [14]:
import torch
print(torch.__version__)

2.9.0+cu126


In [15]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4


# *Creating a Tensor*

In [16]:
tens= torch.empty(5,5)
tens
# using numpy

tensor([[0.0000e+00, 0.0000e+00, 1.8013e-25, 0.0000e+00, 7.3806e-23],
        [0.0000e+00, 5.9819e-27, 4.4145e-41, 1.4013e-45, 0.0000e+00],
        [5.6052e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [17]:
type(tens)

torch.Tensor

In [18]:
torch.zeros_like(tens) #same shape as tens


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
# We can initiate with zeros or ones too
torch.zeros(5,5)
torch.ones(5,5)


tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [20]:
#random values between zero to one
torch.rand(3,4) #uniform distribution

tensor([[0.7469, 0.5211, 0.6205, 0.9558],
        [0.7590, 0.8562, 0.5876, 0.7703],
        [0.2927, 0.1805, 0.0139, 0.4738]])

In [21]:
# if we want random values but we also want reproducibility , like same tensor again . use seed value
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [22]:
torch.manual_seed(42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [23]:
torch.tensor([[5,6,5],[6,5,6]])

tensor([[5, 6, 5],
        [6, 5, 6]])

In [24]:
#identity matrix
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [25]:
torch.diag(torch.ones(3))
#torch.diag(torch.tensor([5,6,5]))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [26]:
torch.arange(0, 10, 2)


tensor([0, 2, 4, 6, 8])

In [27]:
torch.linspace(0, 2, steps=5)


tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000])

In [28]:
torch.logspace(0, 2, steps=5)


tensor([  1.0000,   3.1623,  10.0000,  31.6228, 100.0000])

In [29]:
torch.tensor([True, False, True])


tensor([ True, False,  True])

In [30]:
x=torch.tensor([[5,6,5],[6,5,6]])
x.shape

torch.Size([2, 3])

In [31]:
torch.rand_like(x,dtype=torch.float32)


tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [32]:
x.dtype

torch.int64

In [33]:
x=torch.tensor([[5,6.0,5.0],[6.0,5.0,6.0]])
x.dtype

torch.float32

In [34]:
x=torch.tensor([[5,6.0,5.0],[6.0,5.0,6.0]],dtype=torch.int32)
x.dtype

torch.int32

In [35]:
x.to(torch.float64)

tensor([[5., 6., 5.],
        [6., 5., 6.]], dtype=torch.float64)

# *Mathematical Operations*

In [36]:
#Addition
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# a + b OR
torch.add(a, b)

tensor([5, 7, 9])

In [37]:
# Subtraction
a - b
torch.sub(a, b)

tensor([-3, -3, -3])

In [38]:
# Multiplication (element-wise)
a * b
torch.mul(a, b)

tensor([ 4, 10, 18])

In [39]:
# Division
a / b
torch.div(a, b)


tensor([0.2500, 0.4000, 0.5000])

In [40]:
# torch.pow(a, 2)
# OR

a ** 2


tensor([1, 4, 9])

In [41]:
# Square root
torch.sqrt(a)

tensor([1.0000, 1.4142, 1.7321])

In [42]:
a

tensor([1, 2, 3])

In [43]:
a+5
# same for minus

tensor([6, 7, 8])

In [44]:
a=a*5
a

tensor([ 5, 10, 15])

In [45]:
a/5

tensor([1., 2., 3.])

In [46]:
a=a+6
a

tensor([11, 16, 21])

In [47]:
a

tensor([11, 16, 21])

In [48]:
a//5

tensor([2, 3, 4])

In [49]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])


In [50]:
c=a**b
c

tensor([  1,  32, 729])

In [51]:
c%b

tensor([1, 2, 3])

In [52]:
d=a-b
d

tensor([-3, -3, -3])

In [53]:
torch.abs(d)

tensor([3, 3, 3])

In [54]:
torch.neg(d)

tensor([3, 3, 3])

In [55]:
temp=a+5/b
temp

tensor([2.2500, 3.0000, 3.8333])

In [56]:
torch.round(temp)

tensor([2., 3., 4.])

In [57]:
torch.ceil(temp)

tensor([3., 3., 4.])

In [58]:
torch.floor(temp)

tensor([2., 3., 3.])

In [59]:
temp=torch.tensor([-2,4,6])

In [60]:
temp

tensor([-2,  4,  6])

In [61]:
torch.clamp(temp,min=0,max=5)

tensor([0, 4, 5])

# Reduction Operation

In [62]:
e=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)
e

tensor([[7., 6., 9., 6.],
        [3., 1., 9., 3.],
        [1., 9., 7., 9.]])

In [63]:
torch.sum(e)

tensor(70.)

In [64]:
torch.sum(e,dim=0)

tensor([11., 16., 25., 18.])

In [65]:
torch.sum(e,dim=1)

tensor([28., 16., 26.])

In [66]:
torch.mean(e)
# can do along the rows and cloumns

tensor(5.8333)

In [67]:
# torch.var(e)
# torch.std(e)
# torch.exp(e)
torch.log(e)
# torch.log10(e)


tensor([[1.9459, 1.7918, 2.1972, 1.7918],
        [1.0986, 0.0000, 2.1972, 1.0986],
        [0.0000, 2.1972, 1.9459, 2.1972]])

In [68]:
torch.sin(e)
# torch.cos(e)
# torch.tan(e)


tensor([[ 0.6570, -0.2794,  0.4121, -0.2794],
        [ 0.1411,  0.8415,  0.4121,  0.1411],
        [ 0.8415,  0.4121,  0.6570,  0.4121]])

In [69]:
torch.argmax(e)
# torch.argmin(e)


tensor(2)

In [70]:
# torch.max(e) position of max number
torch.min(a) # pos of min number


tensor(1)

In [71]:
a = torch.tensor([[1, 2, 3],[4, 5, 6]]) #2x3
b = torch.tensor([[4, 5],[ 2, 3],[1, 2]]) #3x2


In [72]:
torch.matmul(a,b) #matrix multiplication
#  also we can do dot product using :
# torch.dot


tensor([[11, 17],
        [32, 47]])

In [73]:
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [74]:
torch.transpose(a,0,1)
# transpose

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [75]:
# determinant
# torch.det(a) for square matrix


In [76]:
# Sample tensors
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([2, 2, 1, 4])

print("a:", a)
print("b:", b)

print("\n--- Element-wise Comparisons ---")

print("a == b :", torch.eq(a, b))
print("a != b :", torch.ne(a, b))

print("a > b  :", torch.gt(a, b))
print("a >= b :", torch.ge(a, b))

print("a < b  :", torch.lt(a, b))
print("a <= b :", torch.le(a, b))

print("\n--- Using Operators (Same result) ---")

print("a == b :", a == b)
print("a != b :", a != b)
print("a > b  :", a > b)
print("a >= b :", a >= b)
print("a < b  :", a < b)
print("a <= b :", a <= b)

print("\n--- Comparison with Scalars ---")

print("a > 2  :", a > 2)
print("a == 3 :", a == 3)

print("\n--- All / Any Conditions ---")

print("All a > 0 :", torch.all(a > 0))
print("All a > 0 :", torch.all(a > 2))
print("Any a > 3 :", torch.any(a > 3))


a: tensor([1, 2, 3, 4])
b: tensor([2, 2, 1, 4])

--- Element-wise Comparisons ---
a == b : tensor([False,  True, False,  True])
a != b : tensor([ True, False,  True, False])
a > b  : tensor([False, False,  True, False])
a >= b : tensor([False,  True,  True,  True])
a < b  : tensor([ True, False, False, False])
a <= b : tensor([ True,  True, False,  True])

--- Using Operators (Same result) ---
a == b : tensor([False,  True, False,  True])
a != b : tensor([ True, False,  True, False])
a > b  : tensor([False, False,  True, False])
a >= b : tensor([False,  True,  True,  True])
a < b  : tensor([ True, False, False, False])
a <= b : tensor([ True,  True, False,  True])

--- Comparison with Scalars ---
a > 2  : tensor([False, False,  True,  True])
a == 3 : tensor([False, False,  True, False])

--- All / Any Conditions ---
All a > 0 : tensor(True)
All a > 0 : tensor(False)
Any a > 3 : tensor(True)


In [77]:

X = torch.tensor([
    [-2.0, -1.0,  0.0],
    [ 1.0,  2.0,  3.0]
])

sigmoid_out = torch.sigmoid(X)

print("Input Matrix:\n", X)
print("Sigmoid Output:\n", sigmoid_out)


Input Matrix:
 tensor([[-2., -1.,  0.],
        [ 1.,  2.,  3.]])
Sigmoid Output:
 tensor([[0.1192, 0.2689, 0.5000],
        [0.7311, 0.8808, 0.9526]])


In [78]:
import torch.nn.functional as F

softmax_row = F.softmax(X, dim=1)

print("Row-wise Softmax:\n", softmax_row)
print("Row-wise Sum:", softmax_row.sum(dim=1))



Row-wise Softmax:
 tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])
Row-wise Sum: tensor([1., 1.])


In [79]:
torch.relu(X)

tensor([[0., 0., 0.],
        [1., 2., 3.]])

# *Inplace Operation*

In [80]:
import torch

a = torch.tensor([1., 2., 3.])

a.add_(2)      # a = a + 2
print(a)

a.mul_(3)      # a = a * 3
print(a)


tensor([3., 4., 5.])
tensor([ 9., 12., 15.])


In [81]:
a = torch.tensor([2., 4., 6.])

a.sub_(1)      # subtraction
a.div_(2)      # division
a.pow_(2)      # power

print(a)


tensor([0.2500, 2.2500, 6.2500])


In [82]:
x = torch.tensor([-2., 0., 3.])

x.relu_()
print(x)
x.sigmoid_()
print(x)
x.tanh_()
print(x)


tensor([0., 0., 3.])
tensor([0.5000, 0.5000, 0.9526])
tensor([0.4621, 0.4621, 0.7409])


In [83]:
t = torch.empty(3)

t.zero_()      # fill with zeros
t.fill_(5)     # fill with constant
print(t)


tensor([5., 5., 5.])


# *Copying and Cloning a Tensor*

In [84]:
a = torch.tensor([1, 2, 3])
b = a          # NOT a copy
b[0] = 100
print(a)       # tensor([100, 2, 3])


tensor([100,   2,   3])


In [85]:
print(id(a))
print(id(b))


135304658883984
135304658883984


In [86]:
a = torch.tensor([1., 2., 3.], requires_grad=True)

b = a.clone()

b[0] = 100
print(a)   # unchanged
print(b)
print(id(a))
print(id(b))

tensor([1., 2., 3.], requires_grad=True)
tensor([100.,   2.,   3.], grad_fn=<CopySlices>)
135304658888064
135304658886704


# *Tesnsor operation on GPU*

In [87]:
import torch
torch.cuda.is_available()

True

In [88]:
device = torch.device('cuda')
device

device(type='cuda')

In [89]:
torch.rand((2,3),device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [90]:
a=torch.rand(2,3) #this is on cpu

In [91]:
a.to(device) #Now a is on GPU

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]], device='cuda:0')

In [92]:
import torch
import time

# Matrix size
N = 5_000

# ---------------- CPU ----------------
print("Running on CPU...")
A_cpu = torch.randn(N, N)
B_cpu = torch.randn(N, N)

start = time.time()
C_cpu = torch.matmul(A_cpu, B_cpu)
end = time.time()

print(f"CPU time: {end - start:.2f} seconds")

# ---------------- GPU ----------------
if torch.cuda.is_available():
    print("\nRunning on GPU...")
    device = torch.device("cuda")

    A_gpu = A_cpu.to(device)
    B_gpu = B_cpu.to(device)

    # warm-up (important for fair timing)
    torch.matmul(A_gpu, B_gpu)
    torch.cuda.synchronize()

    start = time.time()
    C_gpu = torch.matmul(A_gpu, B_gpu)
    torch.cuda.synchronize()   # wait for GPU to finish
    end = time.time()

    print(f"GPU time: {end - start:.2f} seconds")
else:
    print("\nCUDA not available")


Running on CPU...
CPU time: 1.80 seconds

Running on GPU...
GPU time: 0.09 seconds


# *Reshaping Tensor*

In [93]:
import torch

# 2D tensor
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original tensor:")
print(x)
print("Shape:", x.shape)   # (2, 3)

# ---------------- reshape ----------------
r = x.reshape(3, 2)
print("\nReshape (2,3) -> (3,2):")
print(r)
print("Shape:", r.shape)

# ---------------- flatten ----------------
f = torch.flatten(x)
print("\nFlatten:")
print(f)
print("Shape:", f.shape)

# ---------------- permute ----------------
p = x.permute(1, 0)
print("\nPermute (transpose):")
print(p)
print("Shape:", p.shape)

# ---------------- unsqueeze ----------------
u = x.unsqueeze(0)
print("\nUnsqueeze at dim=0:")
print(u)
print("Shape:", u.shape)   # (1, 2, 3)

# ---------------- squeeze ----------------
s = u.squeeze(0)
print("\nSqueeze back:")
print(s)
print("Shape:", s.shape)   # (2, 3)


Original tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

Reshape (2,3) -> (3,2):
tensor([[1, 2],
        [3, 4],
        [5, 6]])
Shape: torch.Size([3, 2])

Flatten:
tensor([1, 2, 3, 4, 5, 6])
Shape: torch.Size([6])

Permute (transpose):
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape: torch.Size([3, 2])

Unsqueeze at dim=0:
tensor([[[1, 2, 3],
         [4, 5, 6]]])
Shape: torch.Size([1, 2, 3])

Squeeze back:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


# pytorch and *numpy*

In [94]:
# Memory is Shared. Change in One will be reflected to the other one
import numpy as np
import torch

np_arr = np.array([[1, 2], [3, 4]], dtype=np.float32)

t = torch.from_numpy(np_arr)
print(t)


tensor([[1., 2.],
        [3., 4.]])


In [95]:
# Memory is Shared. Change in One will be reflected to the other one
t = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

np_arr = t.numpy()
print(np_arr)


[[1. 2.]
 [3. 4.]]
